# coding: utf-8

"""
    NFL v3 Stats

    NFL rosters, player stats, team stats, and fantasy stats API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.fantasy_defense_game import FantasyDefenseGame  # noqa: E501
from swagger_client.rest import ApiException


class TestFantasyDefenseGame(unittest.TestCase):
    """FantasyDefenseGame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFantasyDefenseGame(self):
        """Test FantasyDefenseGame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fantasy_defense_game.FantasyDefenseGame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
