# coding: utf-8

"""
    NFL v3 Stats

    NFL rosters, player stats, team stats, and fantasy stats API.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.game import Game  # noqa: E501
from swagger_client.rest import ApiException


class TestGame(unittest.TestCase):
    """Game unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGame(self):
        """Test Game"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.game.Game()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
